apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-c0lu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jftl-tenant/appstudio/devfile-sample-python-basic-c0lu@sha256:672a08d4b3aa75ea0d6b12b090d5c50618936263ab054c917460181e79b0598e
        name: my-python
        resources: {}
status: {}
