apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-c0lu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-c0lu
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-c0lu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-c0lu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-c0lu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jftl-tenant/appstudio/devfile-sample-python-basic-c0lu@sha256:f81e01deeae95a486cf2bd655dd64c9170741f55c23039b4f17b02d326660ea7
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
